on: [push, pull_request]

name: Lints

jobs:
  test:
    name: Layout and unit tests
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get -y install xvfb fluxbox
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - name: Start XVFB and run tests
        run: |
          export DISPLAY=:1
          Xvfb :1 -screen 0 1920x1080x24 &
          fluxbox -display :1 &
          cargo test --release
      - name: Cleanup XVFB processes
        if: always()
        run: ./.github/scripts/cleanup-xvfb.sh

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
